#!/bin/bash

DB_USER=`relation-get user`
DB_PASSWORD=`relation-get password`
DB_HOST=`relation-get host`

sed -i.bak "s/host:\ .*$/host:\ $DB_HOST/g" -e "s/user:\ .*$/user:\ $DB_USER/g" -e "s/pass:\ .*$/pass:\ $DB_PASSWORD/g" /opt/cloudfoundry-server/vcap/services/mysql/config/mysql_node.yml

INSTALL_DIR='/opt/cloudfoundry-server'
cd $INSTALL_DIR/vcap
export HOME=/root
export PATH=$PATH:/var/lib/gems/1.9.1/bin

exit 0
