#!/bin/bash

############################################################################################################
# Debugging information
############################################################################################################
set -ux


############################################################################################################
# Set the language
############################################################################################################
LANG=en_US.UTF-8


############################################################################################################
# Dependency and utility packages
############################################################################################################
apt-add-repository ppa:facter-plugins/ppa
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y install debconf-utils python-software-properties pwgen facter facter-customfacts-plugin curl


############################################################################################################
# Global variables
############################################################################################################
# MySQL
MYSQL_ROOT_PASSWORD=`pwgen -N1`
MYSQL_TOKEN=`pwgen -N1`

# DynDNS
USE_DYNDNS="false"
DYNDNS_USERNAME="xxxxx"
DYNDNS_PASSWORD="xxxxx"
DYNDNS_HOSTNAME="xxxxx"

# CloudFoundry Server
CF_SERVER_IP=`facter ipaddress`
NATS_USERNAME="natsadmin"
NATS_PASSWORD=`pwgen -N1`
NATS_DEFAULT_PORT="4222"


############################################################################################################
# Add repositories
############################################################################################################
apt-add-repository ppa:cloudfoundry/ppa
apt-get -y update


############################################################################################################
# Preseed variables
############################################################################################################

# Mysql
echo debconf mysql-server/root_password password ${MYSQL_ROOT_PASSWORD}| /usr/bin/debconf-set-selections
echo debconf mysql-server/root_password_again password ${MYSQL_ROOT_PASSWORD}| /usr/bin/debconf-set-selections

# Postfix
echo debconf postfix/main_mailer_type select No configuration | /usr/bin/debconf-set-selections

# DynDNS
if [ "${USE_DYNDNS}" = "true" ];then
   API_VERSION="2008-02-01"
   METADATA_URL="http://169.254.169.254/$API_VERSION/"
   public_ip=$(curl -s "$METADATA_URL"/meta-data/public-ipv4)
   response=$(curl -s http://"${DYNDNS_USERNAME}":"${DYNDNS_PASSWORD}"@members.dyndns.org/nic/update?hostname="${DYNDNS_HOSTNAME}"&myip=$public_ip&wildcard=NOCHG&mx=NOCHG&backmx=NOCHG)
fi

# CloudFoundry
echo debconf cloudfoundry-server/use_dyndns boolean ${USE_DYNDNS} | /usr/bin/debconf-set-selections
echo debconf cloudfoundry-server/hostname string api.${DYNDNS_HOSTNAME} | /usr/bin/debconf-set-selections
echo debconf cloudfoundry-server-dea/ip string ${CF_SERVER_IP} | /usr/bin/debconf-set-selections
echo debconf cloudfoundry-server/ip string ${CF_SERVER_IP} | /usr/bin/debconf-set-selections

fact-add mysql-root-password ${MYSQL_ROOT_PASSWORD}
fact-add mysql-token ${MYSQL_TOKEN}
fact-add use-dyndns ${USE_DYNDNS}
fact-add dyndns-username ${DYNDNS_USERNAME}
fact-add dyndns-password ${DYNDNS_PASSWORD}
fact-add dyndns-hostname api.${DYNDNS_HOSTNAME}
fact-add nats-username ${NATS_USERNAME}
fact-add nats-password ${NATS_PASSWORD}
fact-add nats-default-port ${NATS_DEFAULT_PORT}


############################################################################################################
# Install CloudFoundry package
############################################################################################################
DEBIAN_FRONTEND=noninteractive apt-get -y install cloudfoundry-server


############################################################################################################
# Configure mysql password for cloudfoundry-server
############################################################################################################
sed -i -e "s/  pass:.*/  pass: ${MYSQL_ROOT_PASSWORD}/" /opt/cloudfoundry-server/vcap/services/mysql/config/mysql_node.yml


############################################################################################################
# Configure all of the gateway services to point to the correct cloud_controller_uri
############################################################################################################
cd /opt/cloudfoundry-server/vcap/services
find -type f | grep yml | xargs sed -i -e "s/.*cloud_controller_uri.*/cloud_controller_uri: api.${DYNDNS_HOSTNAME}/"


############################################################################################################
# Stop CloudFoundry ( due to LP:810808 )
############################################################################################################
service cloudfoundry-server stop
cd /opt/cloudfoundry-server/vcap && HOME=/root rake db:migrate && cd -


############################################################################################################
# Open the necessary firewall/ACL ports
############################################################################################################
if [ -x /usr/bin/open-port ]; then
   open-port 80/TCP
   open-port 443/TCP
   open-port ${NATS_DEFAULT_PORT}/TCP
fi

exit 0
