#!/bin/bash

set -ux

# Fixing what I hope is a temporary issue in the latest oneiric
[ -d /var/cache/debconf ] || mkdir -p /var/cache/debconf
[ -e /var/cache/debconf/config.dat ] || touch /var/cache/debconf/config.dat
apt-get update
apt-get -y dist-upgrade



############################################################################################################
# Set the language
############################################################################################################
LANG=en_US.UTF-8


############################################################################################################
# Dependency and utility packages
############################################################################################################
DEBIAN_FRONTEND=noninteractive apt-get -y install debconf-utils python-software-properties pwgen facter facter-customfacts-plugin curl


############################################################################################################
# Global variables
############################################################################################################
MYSQL_ROOT_PASSWORD=`pwgen -N1`
USE_DYNDNS="true"
DYNDNS_USERNAME="iamfuzz"
DYNDNS_PASSWORD="testing123"
DYNDNS_HOSTNAME="cloud-foundry.dyndns.org"

############################################################################################################
# Add repositories
############################################################################################################
# There seems to be a bug in apt-add-repository where it is picking "sid" as the version as opposed to
# the real one  ( oneiric at the time of this writing ).  Installing the repo and keys manually to work
# around the issue. ( Bug 816169 in launchpad.net )
# LP: 816169
rm -f /etc/apt/sources.list.d/cloudfoundry-ppa-oneiric.list
echo deb http://ppa.launchpad.net/cloudfoundry/testing/ubuntu oneiric main  >> /etc/apt/sources.list.d/cloudfoundry-ppa-oneiric.list
echo deb-src http://ppa.launchpad.net/cloudfoundry/testing/ubuntu oneiric main  >> /etc/apt/sources.list.d/cloudfoundry-ppa-oneiric.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E9F24FECE9E376B3B981F0FC8E42119F7BC0B676
# apt-add-repository ppa:cloudfoundry/ppa
apt-get -y update


############################################################################################################
# Preseed variables
############################################################################################################

# Mysql
echo debconf mysql-server/root_password password ${MYSQL_ROOT_PASSWORD}| /usr/bin/debconf-set-selections
echo debconf mysql-server/root_password_again password ${MYSQL_ROOT_PASSWORD}| /usr/bin/debconf-set-selections

# Postfix
echo debconf postfix/main_mailer_type select No configuration | /usr/bin/debconf-set-selections

# DynDNS
if [ "${USE_DYNDNS}" = "true" ];then
   echo debconf cloudfoundry-server/use_dyndns boolean ${USE_DYNDNS} | /usr/bin/debconf-set-selections
   echo debconf cloudfoundry-server/username string ${DYNDNS_USERNAME} | /usr/bin/debconf-set-selections
   echo debconf cloudfoundry-server/password password ${DYNDNS_PASSWORD} | /usr/bin/debconf-set-selections
   echo debconf cloudfoundry-server/hostname string ${DYNDNS_HOSTNAME} | /usr/bin/debconf-set-selections
   API_VERSION="2008-02-01"
   METADATA_URL="http://169.254.169.254/$API_VERSION/"
   public_ip=$(curl -s "$METADATA_URL"/meta-data/public-ipv4)
   response=$(curl -s http://"${DYNDNS_USERNAME}":"${DYNDNS_PASSWORD}"@members.dyndns.org/nic/update?hostname="${DYNDNS_HOSTNAME}"&myip=$public_ip&wildcard=NOCHG&mx=NOCHG&backmx=NOCHG)
fi

fact-add mysql-root-password ${MYSQL_ROOT_PASSWORD}
fact-add use-dyndns ${USE_DYNDNS}
fact-add dyndns-username ${DYNDNS_USERNAME}
fact-add dyndns-password ${DYNDNS_PASSWORD}


############################################################################################################
# Install CloudFoundry package
############################################################################################################

DEBIAN_FRONTEND=noninteractive apt-get -y install ruby1.9.1-full=1.9.2.180-3ppa2 ruby1.9.1=1.9.2.180-3ppa2 libruby1.9.1-dbg=1.9.2.180-3ppa2 ruby1.9.1-dev=1.9.2.180-3ppa2 ruby1.9.1-examples=1.9.2.180-3ppa2 ri1.9.1=1.9.2.180-3ppa2 libtcltk-ruby1.9.1=1.9.2.180-3ppa2

DEBIAN_FRONTEND=noninteractive apt-get -y install cloudfoundry-server


############################################################################################################
# Stop CloudFoundry ( due to LP:810808 )
############################################################################################################

service cloudfoundry stop


############################################################################################################
# Open the necessary firewall/ACL ports
############################################################################################################
if [ -x /usr/bin/open-port ]; then
   open-port 80/TCP
   open-port 443/TCP
fi

exit 0
