#!/bin/bash

############################################################################################################
# Debugging information
############################################################################################################

set -ux

############################################################################################################
# Get the remote hostname that should have been saved on the _joined_ hook so we can restore the config
#  exit 0 if not.  
############################################################################################################

REMOTE_MONGODB_HOSTNAME=`facter mongodb_hostname`

[ -z ${REMOTE_MONGODB_HOSTNAME} ] && exit 0


############################################################################################################
# Make the changes
############################################################################################################

sed -i -e "s/${REMOTE_MONGODB_HOSTNAME}/localhost/" /opt/cloudfoundry-server/vcap/services/mongodb/lib/mongodb_service/mongodb_node.rb
find /opt/cloudfoundry-server/vcap/services/mongodb/spec -type f -exec sed -i -e "s/${REMOTE_MONGODB_HOSTNAME}/localhost/" {} \;


############################################################################################################
# Restart CloudFoundry so the new settings take effect.
############################################################################################################

service cloudfoundry-server restart


# Open mongodb port
[ -x /usr/bin/close-port ] && close-port 27017/TCP

