#!/bin/bash

############################################################################################################
# Debuggin information
############################################################################################################

set -ux

############################################################################################################
# Get the remote mongodb and exit normally if not found
############################################################################################################

REMOTE_MONGODB_HOSTNAME=`relation-get hostname`
[ -z ${REMOTE_MONGODB_HOSTNAME} ] && exit 0

############################################################################################################
# Save the value of the mongodb hostname as this is going to be needed to reverse the changes if/when
#  we need to do such a thing. 
############################################################################################################

fact-add mongodb_hostname ${REMOTE_MONGODB_HOSTNAME}

############################################################################################################
# VMWare hardcoded localhost on their code so, let's change that to our new mongodb server
############################################################################################################

sed -i -e "s/localhost/${REMOTE_MONGODB_HOSTNAME}/" /opt/cloudfoundry-server/vcap/services/mongodb/lib/mongodb_service/mongodb_node.rb
find /opt/cloudfoundry-server/vcap/services/mongodb/spec -type f -exec sed -i -e "s/localhost/${REMOTE_MONGODB_HOSTNAME}/" {} \;

############################################################################################################
# Restart CloudFoundry server so the new settings take effect.
############################################################################################################

service cloudfoundry-server restart

# Open mongodb port
[ -x /usr/bin/open-port ] && open-port 27017/TCP

