#!/bin/bash

set -ux

############################################################################################################
# Establish _our_ hostname, username and password
#  This information is going to be used by the _other_ side of this relationship
#  to grant admin access to _that_ database using _this_ host, user and password
############################################################################################################

MYSQL_CF_ADMIN_USER="cf-root"
MYSQL_CF_ADMIN_PASSWORD=`facter mysql-root-password`
LOCAL_HOSTNAME=`facter fqdn`

relation-set host="${LOCAL_HOSTNAME}" user="${MYSQL_CF_ADMIN_USER}" password="${MYSQL_CF_ADMIN_PASSWORD}"

