#!/bin/bash

############################################################################################################
# Debuggin information
############################################################################################################

set -ux

############################################################################################################
# Get the remote redis or exit normally if not found
############################################################################################################

REMOTE_REDIS_HOSTNAME=`relation-get hostname`
[ -z ${REMOTE_REDIS_HOSTNAME} ] && exit 0

############################################################################################################
# Save the value of the redis hostname as this is going to be needed to reverse the changes if/when
#  we need to do such a thing.
############################################################################################################

fact-add redis_hostname ${REMOTE_REDIS_HOSTNAME}

############################################################################################################
# VMWare hardcoded localhost on their code so, let's change that to our new redis server
############################################################################################################

sed i -e "s/127.0.0.1/${REMOTE_REDIS_HOSTNAME}/" /opt/cloudfoundry-server/vcap/services/redis/spec/node_spec.rb


############################################################################################################
# Restart CloudFoundry server so the new settings take effect.
############################################################################################################

service cloudfoundry-server restart

# Open redis port
[ -x /usr/bin/open-port ] && open-port 6379/TCP

