#!/bin/bash

############################################################################################################
# startvcap:
#   - &start_vcap |
#     INSTALL_DIR='/opt/cloudfoundry-server'
#     source /etc/rvmrc
#     source /etc/profile
#     export rvm_trust_rvmrcs_flag=1
#     cd $INSTALL_DIR/vcap
#     export HOME=/root
#     export PATH=$PATH:/var/lib/gems/1.9.1/bin
#     rake db:migrate
#     bin/vcap start

set -eux

INSTALL_DIR='/opt/cloudfoundry-server'
#source /etc/rvmrc
#source /etc/profile
export rvm_trust_rvmrcs_flag=1
cd $INSTALL_DIR/vcap
export HOME=/root
export PATH=$PATH:/var/lib/gems/1.9.1/bin
#rake db:migrate
bin/vcap start

exit 0
